const about = [
    {
        name: "naruto",
        namee:"Naruto : Shippuden",
        kapakfoto: "https://cutewallpaper.org/21/all-naruto-shippuden-characters/Naruto-Shippuden-All-Characters-Wallpapers-Wallpaper-Cave.png",
        main: {
            foto: "https://wallpapers.com/images/featured-full/cool-naruto-jycvpon5xnv27t7m.jpg", article: ` "Naruto Shippuden," "Naruto" serisinin devamı niteliğinde olan bir anime ve manga serisidir. İlk seri olan "Naruto," Naruto Uzumaki'nin gençlik yıllarını ve arkadaşlarıyla beraber büyüme sürecini anlatırken, "Naruto Shippuden" ise Naruto'nun yetişkinlik dönemini ve daha ciddi, karmaşık olayları ele alır."Naruto Shippuden," Naruto'nun 3 yıl süren yoğun bir antrenmandan sonra geri dönmesiyle başlar. Artık daha güçlü ve olgun bir ninja olan Naruto, amacı eski öğretmeni Kakashi Hatake liderliğindeki Takım 7 ile beraber Sasuke Uchiha'yı geri getirmek ve kötü yollara sapmış eski arkadaşını kendi köyüne geri döndürmektir.Ancak zaman içinde olaylar, Sasuke'yu kurtarma amacını aşan bir boyut kazanır. Büyük bir tehdit olarak gördüğümüz Akatsuki adlı suç örgütü, Bijuu adı verilen efsanevi canavarları ele geçirerek dünyayı kaosa sürüklemeye çalışır. Naruto ve arkadaşları, dünyayı korumak için güçlerini birleştirir ve Akatsuki'ye karşı mücadele eder.Bu süreçte Naruto, geçmişindeki sırlarla yüzleşir, kendi gücünü ve özünü anlamak için bir iç yolculuğuna çıkar ve insanlar arasında gerçek bir bağ kurarak hayatlarını değiştirir. Sasuke'nin değişimi ve ittifakların kurulması, seriyi daha da derinleştirir ve karakterlerin gelişimleri büyük önem taşır."Naruto Shippuden," dostluk, cesaret, umut, sadakat ve affetmenin güçlü temalarını işlerken, muhteşem dövüş sahneleri ve duygusal anlarla dolu zengin bir hikaye sunar. Seri, Naruto Uzumaki'nin ve diğer karakterlerin yükselişini ve olgunlaşmasını izlemek için eşsiz bir fırsat sunar.`     
        },
        karakterler: [
           
            {nickname:"Naruto Uzumaki",foto:"https://sun1-90.userapi.com/s/v1/ig2/kS5A_fmQ_DZiu4uDzapnuN_ET6PTWgdan_9Ys-1pNG1c9nDVawfD41oiDokwrMAUVS3xQzeXKQ-eBKKyjrt_S8Eu.jpg?size=400x400&quality=95&crop=261,177,533,533&ava=1", sayi:1,article:`Naruto Uzumaki, "Naruto" serisinin baş karakteridir ve hikayenin merkezinde yer alır. İlk başta çocuksu ve hiperaktif bir kişilik olarak tanıtılsa da, zamanla olgunlaşan, güçlenen ve cesur bir ninja haline gelir. Başta yalnız ve dışlanmış hisseder, çünkü içinde Kyuubi adında kuyruklu canavar mühürlenmiştir. Bu nedenle, köy sakinleri ona ve Kyuubi'ye şüpheyle yaklaşır ve Naruto'yu hor görürler.Naruto'nun en büyük hedefi, Konoha'nın en güçlü ve saygın lideri olan Hokage olmaktır. Bu hedefi, kendisine verilen görevleri, arkadaşlarını korumayı ve köyüne hizmet etmeyi motive eder. Zorluklara karşı pes etmeyen ve her zaman iyilik ve adalet için mücadele eden bir karakterdir.Naruto'nun en güçlü özelliklerinden biri, chakra denilen doğal enerjiyi kontrol edebilme yeteneğidir. Çeşitli ninjutsu, genjutsu ve taijutsu tekniklerini kullanarak düşmanlarını alt eder. Ayrıca, onun özel tekniklerinden biri olan "Kage Bunshin No Jutsu," düşmanları şaşırtma ve çeşitli zorlu görevleri yerine getirme konusunda ona büyük avantaj sağlar.`},
            {nickname:"Sasuke Uchiha",foto:"https://i.pinimg.com/originals/5f/7e/a4/5f7ea4388576870a5130e920f31c9401.jpg",sayi:2, article:`Sasuke, Uchiha Klanı'ndan gelir ve genç yaşta ailesinin trajik bir şekilde öldürülmesine tanık olmuştur. Bu olay, onun içinde intikam ateşini körükler ve en güçlü olmayı hedefler. Sasuke, genç yaşta kendisine verilen görevleri yerine getirme konusunda oldukça yetenekli bir ninja olarak yetişir. Aynı zamanda, üstün yeteneklere sahip bir Uchiha olmasının verdiği özgüvene sahiptir.Sasuke'nin en büyük hedefi, ailesini öldüren kişi olan ağabeyi Itachi Uchiha'ya intikam almaktır. Bu nedenle, Itachi'yi yenmek ve klanının itibarını geri getirmek için Orochimaru adındaki karanlık bir ninjanın teklifini kabul eder ve Konoha Köyü'nden ayrılır.Sasuke karakteri, karmaşık kişiliği ve duygusal iç çatışmaları ile dikkat çeker. Seri boyunca, geçmişinin izlerini silmek, yeni bir amaç bulmak ve kim olduğunu anlamak için zorlu bir mücadele verir. Sasuke'nin hikayesi, intikamın yol açabileceği yıkıcı sonuçlar ve gerçek arkadaşlığın değeri hakkında önemli bir mesaj sunar.`},
            {nickname:"Sakura Haruna",foto:"https://static.fandomspot.com/images/04/31486/16-sakura-haruno-naruto-shippuden-anime.jpg",sayi:3,article:`Sakura Haruno, hikayenin ana kadın karakterlerinden biridir. Seri boyunca, Naruto ve Sasuke'nin yakın arkadaşı ve takım arkadaşı olarak dikkat çeker.Sakura, güçlü bir ninja olma hedefiyle yetişen bir tıp-ninjadır. Serinin başlangıcında, Sasuke'ye olan hayranlığı ve ona duyduğu ilgi, Naruto'ya karşı soğuk bir tavır takınmasına neden olur. Başlangıçta fiziksel olarak zayıf ve yeteneksiz gibi görünse de, zamanla karakter gelişimine ve güçlenmeye başlar.Hikaye ilerledikçe, Sakura, daha güçlü olmak için eğitim almaya karar verir ve Tsunade adında efsanevi bir tıp-ninja ve aynı zamanda Konoha'nın beşinci Hokage'si olan birinin öğrencisi olur. Tsunade'den aldığı eğitimle tıbbi ninjutsu alanında uzmanlaşır ve kritik anlarda takım arkadaşlarını iyileştirmek için büyük bir önem taşır.Sakura, kuvvetli ve cesur bir karakterdir, ancak bazen duygusal olarak da zayıflıklar gösterir. Sasuke'ye olan hislerini ve onun gitmesine olan özlem ve üzüntüsünü içsel olarak yaşar. Ancak zamanla, arkadaşlarının güvenini ve takım ruhunu kazanarak daha güçlü bir kişi olur.`},
            {nickname:"Hinata Hyuga",foto:"https://i.pinimg.com/originals/ca/dd/7b/cadd7bbcd43117fb5869a29fa32a5b76.jpg", sayi:4,article:`Hinata Hyuga, Hyuga klanına mensup olan Hinata, Gizli Yaprak Köyü'nün saygın ailelerinden birine aittir.Hinata'nın kişiliği, sakin, utangaç ve içine kapanık bir yapıdadır. Çocukluk yıllarında, klanının yüksek beklentileri ve bireysel zorluklarla mücadele etmiştir. Ancak zamanla, kendisini geliştirerek ve Naruto Uzumaki ile tanıştıktan sonra, daha güçlü bir kişi haline gelmiştir.Naruto'ya olan hayranlığı ve onun cesaretine olan hayranlığı, Hinata'yı motive eder ve onu daha da güçlü bir kunoichi yapar. Naruto'nun cesaret ve azmine olan inancı, Hinata'yı kendi iç gücünü keşfetmeye teşvik eder.Hinata, Byakugan adı verilen özel bir göz tekniğine sahiptir. Bu teknik, uzak mesafelerdeki hareketleri ve chakra akışını algılamasına yardımcı olur ve savaşta büyük avantaj sağlar.Hinata'nın, hem kişisel gelişimi hem de ninja yetenekleriyle ilgili hikayesi, Naruto Shippuden serisinin önemli ve duygusal yönlerinden birini oluşturur. Gücünü keşfetme ve sevdikleri için savaşma yolculuğu, hayranlar arasında onu sevilen bir karakter haline getirir.`},
            {nickname:"Kakashi Hatake",foto:"https://i.pinimg.com/originals/8d/7d/16/8d7d163da5e1771dc2f3fd9f041660c1.jpg", sayi:5,article:`Kakashi Hatake, gizemli görünüşü ve yüzündeki maske nedeniyle genellikle diğer karakterler ve izleyiciler tarafından merakla karşılanır. Kakashi, oldukça yetenekli ve tecrübeli bir jonin (yüksek seviyede ninja) olarak tanınır. "Kopya Ninja" olarak anılan ünvanını, binlerce jutsu ve teknikleri anında kopyalayabilme yeteneğine sahip olmasından alır. Bunun yanı sıra, "Sharingan" adı verilen özel göz tekniğini kullanarak da rakiplerini etkisiz hale getirebilir.Görünenin aksine, Kakashi oldukça duygusal ve sorumlu bir karakterdir. Özellikle takım arkadaşlarına ve öğrencilere karşı büyük bir bağlılık hisseder. Naruto, Sasuke ve Sakura gibi takım arkadaşlarına liderlik ederken, onları sert ancak adil bir şekilde eğitir ve destekler. Ayrıca, Naruto'ya kendi zorlu geçmişiyle başa çıkmak için önemli hayat dersleri verir.`},
            {nickname:"Minato Namikaze",foto:"https://yt3.ggpht.com/ytc/AKedOLSzGmhowtf9oWzl6ArtMoxtrmEuyK7Hi0pH8CxmQw=s900-c-k-c0x00ffffff-no-rj", sayi:6,article:`Minato Namikaze, Naruto Shippuden'deki önemli karakterlerden biridir. Aynı zamanda "Dördüncü Hokage" olarak da bilinir. Minato, Gizli Yaprak Köyü'nün önde gelen ninja yeteneklerinden biridir.Genç yaşta gösterdiği olağanüstü yetenekler sayesinde hızla yükselmiş ve Jonin unvanını kazanmıştır. Efsanevi Sanninlerden Jiraiya tarafından eğitilerek güçlü teknikler ve taktikler öğrenmiştir.Minato, Takım Minato'nun lideri olarak Rin Nohara, Kakashi Hatake ve Obito Uchiha ile birlikte çalışmıştır. Bu takım, önemli görevler üstlenerek Gizli Yaprak Köyü'ne hizmet etmiştir.Köyünün sevgilisi ve saygın bir üyesi olarak, Minato, Dördüncü Hokage olarak atanmıştır. Bilgeliği, adaleti ve cesaretiyle tanınan bir liderdir ve halkının saygısını kazanmıştır.Minato Namikaze, Naruto için önemli bir figür olmuş ve Naruto'nun hayatındaki kahramanlık mirasının temel taşlarından birini oluşturmuştur.`},
            {nickname:"Kushina Uzumaki",foto:"https://i.pinimg.com/736x/39/07/3b/39073b48863e7a2fa8a563a9323859e8.jpg",sayi:7, article:`Kushina Uzumaki, Uzumaki Klanı'ndan gelerek güçlü bir chakra mirasına sahip olan Kushina, aynı zamanda uzun kırmızı saçları ve mavi gözleriyle tanınır.Kushina'nın çocukluğu, Kumogakure (Gizli Bulut Köyü) tarafından rehin alınmasıyla gölgelenir. Uzumaki Klanı'nın güçlerini ele geçirmek isteyen Kumogakure, Kushina'ya işkence yapar. Bu zorlu süreçte bile, Kushina'nın güçlü iradesi ve dayanıklılığı dikkat çeker.Naruto Shippuden serisinde, flashback sahnelerinde, Kushina'nın Minato Namikaze ile nasıl tanıştığı ve aşık olduğu hikayesi anlatılır. Minato ile olan ilişkisi, bir görev sırasında tanıştıkları ve zamanla birbirlerine olan duygusal bağlarının güçlendiği şeklinde anlatılır. İkisi, birbirlerini destekleyerek ve güçlü bir çift olarak tanınırlar.`},
            {nickname:"Gaara",foto:"https://i.pinimg.com/originals/f1/45/06/f145066587ce8bdceae0b3dd2b5b62d9.jpg", sayi:8,article:`Gaara, Kumogakure'nin Kazekage'si olan dördüncü çocuk olarak doğmuştur. Gaara, Tailed Beast Shukaku'nun mührü altına alınmış bir Jinchuriki'dir. Babası tarafından Tailed Beast'in mührünün konulması ve annesinin ölümü nedeniyle acı dolu bir çocukluk geçirir. Bu acı dolu geçmiş nedeniyle, Gaara içindeki Shukaku'nun etkisiyle şiddet dolu biri haline gelir . Diğer insanlarla kurduğu bağlara güvenmeyen ve sık sık yalnızlığa sığınan bir kişilik kazanır.Ancak Naruto ve arkadaşlarıyla tanıştıktan sonra, Gaara'nın yaşamında önemli bir değişim başlar. Naruto'nun sıcaklığı ve arkadaşlığı sayesinde, yavaş yavaş içindeki karanlık tarafı azalır ve gerçek bir lider olma yolunda ilerler.Gaara, gücünü ve liderlik yeteneklerini kullanarak Kumogakure'yi ileriye taşır ve insanlarla ilişki kurmada büyük adımlar atar. Ayrıca Naruto'nun örnek alınacak bir arkadaşı ve lider olarak da öne çıkar.`},
            {nickname:"Temari",foto:"https://i.pinimg.com/originals/61/57/84/615784a4f7c15ceb75241f715e7ab423.jpg", sayi:9,article:`Temari, güçlü rüzgar jutsuları ve taktiksel zekasıyla tanınır. Kumogakure'nin Kazekage'sinin büyük kızıdır ve Kum Village'ın Üç Kardeşi'nden biridir.Temari, cesur, soğukkanlı ve yetenekli bir ninjadır. Rüzgar elementini ustaca kullanarak düşmanlarına karşı etkili saldırılar gerçekleştirir. Aynı zamanda liderlik yetenekleri sayesinde Kumogakure'nin saygın bir üyesi olarak bilinir.Naruto ve arkadaşlarıyla tanıştıktan sonra, özellikle Shikamaru Nara ile yakın bir arkadaşlık kurar. Bu ilişki, Temari'nin karakter gelişimine katkıda bulunur ve onu daha anlayışlı ve fedakar bir kişi haline getirir.Temari, güçlü kadın karakterlerden biri olarak, Naruto Shippuden'deki önemli rolüyle hatırlanır ve hayranlar tarafından sevilir. O, cesareti ve yetenekleriyle diğer kadın ninja adaylarına da ilham verir.`},
            {nickname:"Kankuro",foto:"https://img1.ak.crunchyroll.com/i/spire1/df505ef922f148a06f6414ace9d858381405188065_full.jpg", sayi:10,article:`Kankurou, Naruto Shippuden animesinde önemli bir karakterdir. Kumogakure'nin Kazekage'sinin ikinci çocuğu ve Kum Village'ın Üç Kardeşi'nden biridir. Büyük kız kardeşi Temari ve küçük kardeşi Gaara ile birlikte büyümüştür.Kankurou, kukla kullanımıyla ünlüdür ve savaşlarda kuklalarını ustaca kullanarak düşmanlarını alt etme kabiliyetine sahiptir. Bu özelliği ona, Kumogakure'nin saygın ninja üyelerinden biri olma şansı verir.Başlangıçta, Kankurou soğuk ve katı bir kişiliğe sahiptir, ancak Naruto ve diğer arkadaşlarıyla tanıştıktan sonra bu görüşü değişir. Özellikle Naruto ve Gaara arasındaki etkileşimler sayesinde, kardeşler arasında daha sıcak bir bağ geliştirir ve birbirlerine daha yakın olurlar.Kankurou, ailesine ve köyüne olan sadakatiyle bilinir. Kumogakure'nin güvenilir bir koruyucusu ve savaşçısı olarak, Gaara'nın karanlık geçmişindeki olaylarda da önemli bir rol oynar.`},
            {nickname:"Jiraiya",foto:"https://i.pinimg.com/originals/1b/1d/17/1b1d17d8350f2108e24f1478421e77a5.jpg", sayi:11,article:`Jiraiya, Naruto Shippuden animesindeki Efsanevi Sannin üyelerinden biridir. Efsanevi Sannin, Konoha'nın (Gizli Yaprak Köyü) en güçlü üç ninjasından oluşan efsanevi bir takımdır. Jiraiya, Tsunade ve Orochimaru, bu ünlü takımın diğer üyeleridir.Jiraiya, güçlü bir savaşçı, büyücü ve ninja akademisinin eski bir hocasıdır. Yetenekleri ve bilgeliği onu shinobi dünyasının en saygın ve güçlü karakterlerinden biri haline getirir.Küçük yaşlardan itibaren Minato Namikaze'nin (Naruto'nun babası) mentorluğunu üstlenen Jiraiya, Minato'nun yeteneklerine ve liderlik potansiyeline inanır. Aynı zamanda Naruto Uzumaki'ye de benzer bir öğretmenlik rolü üstlenir. Naruto'ya sadece bir öğrenci olarak değil, aynı zamanda bir baba figürü olarak yaklaşır ve onu korur.Jiraiya'nın öğrencisi Naruto, onun onurlu ve cesur kişiliği sayesinde büyük bir ilham kaynağıdır. Jiraiya, Naruto'ya eğitim verirken ona özgürlük, arkadaşlık ve diğer önemli yaşam derslerini öğretir.`},
            {nickname:"Tsunade",foto:"https://i.pinimg.com/originals/97/ee/66/97ee66b4bda917fca19813532e303139.jpg",sayi:12, article:`Tsunade, Naruto'nun efsanevi Hokage olan büyükbabası Hashirama Senju'nun torunudur ve aynı zamanda Uzumaki Naruto'nun uzaktan akrabasıdır. Ailesinin birçok üyesi savaşta hayatını kaybettiği için, Tsunade acı dolu bir geçmişe sahiptir ve bu da onu uzun süre insanlardan uzaklaştırmıştır.Tsunade, tıbbi ninjutsu konusunda büyük bir uzmandır ve eşsiz bir iyileştirme yeteneğine sahiptir. Aynı zamanda güçlü bir savaşçıdır ve devasa bir fiziksel güce sahiptir. Özellikle elleriyle yaptığı şiddetli darbeler, yıkıcı güce sahip olabilir. Naruto Shippuden'da, Tsunade'nin liderliğinde, Konohagakure'yi tehdit eden pek çok zorlu olayla başa çıkar. Düşman saldırıları, iç ve dış tehditlerle mücadele ederken, onun liderliği ve tıbbi yetenekleri hayatta kalmaları için önemli bir rol oynar.`},
            {nickname:"Orochimaru",foto:"https://pbs.twimg.com/media/EjtDPufWoAQrNNy?format=jpg&name=large",sayi:13, article:`Gençlik yıllarında Orochimaru, büyük bir potansiyele sahip bir ninjaydı ve özellikle tıbbi ninjutsu ve zehirli teknikler konusunda uzmandı. Eğitmeni, Hiruzen Sarutobi (Üçüncü Hokage) idi ve Hiruzen onun için bir baba figürü gibiydi. Ancak Orochimaru, gücü elde etmek ve ölümsüzlük arayışı nedeniyle karanlık yollara sapmıştır.Orochimaru'nun en belirgin özelliği, başkalarının bedenlerini ele geçirerek ölümsüzlüğe ulaşmaya çalışmasıdır. Bu nedenle, pek çok kişiyi deneyler için kaçırmış ve onlardan faydalanmıştır. Orochimaru'nun beden değiştirme yeteneği sayesinde genç ve güçlü kalmış ve yıllarca yaşamıştır.Ancak, serinin ilerleyen bölümlerinde Orochimaru'nun karakterinde değişiklikler meydana gelir. Kendisinin tamamen kötü olmadığı ve geçmişindeki travmatik olayların onu şekillendirdiği anlaşılır. Hatta daha sonra Naruto'nun yanında savaşan bir müttefike dönüşür.`},
            {nickname:"Hashimara Senju",foto:"https://i.pinimg.com/736x/31/e7/67/31e7676f62c3956f8904c27a575554ee.jpg", sayi:14,article:`Hashirama'nın en belirgin özelliği, Mokuton Kekkei Genkai'sini kullanabilmesidir. Bu, ağaç benzeri yeteneklerle doğa manipülasyonunu içeren nadir bir yetenektir. Onun Mokuton yetenekleri, devasa ağaçlar ve bitkiler oluşturmasına izin verir ve savaşta büyük avantaj sağlarAyrıca, Hashirama'nın olağanüstü bir iyileştirme yeteneği vardır. Bunun sayesinde, savaşta yaralanan ve ölümcül yaralanmalara maruz kalan kişileri bile kurtarabilirdi. Bu, "Tanrısal Yetenek" olarak da bilinir ve Hashirama'yı savaşta etkili bir lider yapar.Hashirama, shinobi dünyasında barış ve işbirliğini teşvik eden bir lider olarak ün yapmıştır. Kendi köyünü ve diğer klanları birleştirerek Konohagakure'nin temellerini atmış ve barış içinde bir arada yaşamalarını sağlamıştır.`},
            {nickname:"Tobirama Senju",foto:"https://i.pinimg.com/736x/d5/70/c7/d570c7a6906f5026619ecd5dd8ce4f3c.jpg", sayi:15,article:`Tobirama, Hokage görevini abisi Hashiramadan devraldıktan sonra, Konohagakure'nin temel politikalarını ve yapısını geliştirmiştir. Ninjaların rütbeleri ve köy içindeki düzenlemeler gibi pek çok sistemi o kurmuştur ve modern ninjutsu'nun temellerini atmıştır.Ayrıca, Tobirama su tarzı ninjutsu konusunda oldukça uzmandır ve güçlü su teknikleri kullanabilir. Su tarzı, su elementi chakra kullanarak rakiplerini kontrol etmeyi ve su dalgaları, su keskinleri gibi etkili saldırılar yapmayı içerir.Tobirama'nın kardeşi Hashirama gibi, o da barışı ve işbirliğini teşvik etmiştir. Ancak, daha gerçekçi ve şüphecil bir kişiliğe sahiptir ve bazı durumlarda daha katı politikalar izlemiştir.Tobirama aynı zamanda Uchiha Klanı ile gergin bir ilişkiye sahiptir. İkinci Hokage olarak, Uchiha Klanı'nın düşmanca bir tutum takındığını düşünmüş ve köyün güvenliği için sert önlemler almıştır. Bu durum, ilerleyen dönemlerde Uchiha Klanı'nın içindeki huzursuzluğun bir nedeni olmuştur.`},
            {nickname:"Sai",foto:"https://i.pinimg.com/736x/63/d7/74/63d774dd85566abb06e20c16483e986c.jpg", sayi:16,article:`Sai'nin gerçek adı "Sai" değildir, çünkü Anbu Kök üyeleri duygusal bağları ve kimliklerini bırakırlar. Sai, çocuk yaşta Anbu Kök'e alınan ve zorlu bir eğitimden geçirilen biridir. Anbu Kök, gizli operasyonları yürütmek için hükümet tarafından kullanılan gizli bir istihbarat birimidir.Sai, insan ilişkileri ve duygular konusunda oldukça eksik bilgiye sahip bir karakterdir. Duygusal bağlar ve arkadaşlık kavramlarını anlamakta güçlük çeker, bu nedenle diğerleriyle iletişim kurmakta zorlanır ve onlara pek hoş davranmaz.Ancak, Naruto ve ekibiyle olan etkileşimleri, Sai'nin duygusal olarak büyümesine ve insanlar arasında bağlar kurmasına yardımcı olur. Naruto'nun pozitif enerjisi ve arkadaşlık duygusu, Sai'nin duygusal dünyasını değiştirir ve ona gerçek dostluk ve aile bağlarının değerini anlatır.`},
            {nickname:"İtachi Uchiha",foto:"https://avatars.mds.yandex.net/i?id=cc67bda25df39879a63a02d6197001d0-5228102-images-thumbs&n=13", sayi:17,article:`Itachi Uchiha, Uchiha Klanı'nın üyesi olan bir ninjadır. Yetenekleri ve zekasıyla ün salmıştır ve shinobi dünyasında bir efsane olarak kabul edilir. Genç yaşta Chunin rütbesini alarak dikkatleri üzerine çekmiş ve hızla yükselmiştir.Itachi, ilerleyen yaşlarda Konohagakure'nin (Yaprağın Köyü) Anbu birimine. İstihbarat toplama ve gizli operasyonlar gibi görevleri başarıyla yerine getirir. Zamanla, Itachi'nin kendisine dayatılan zorlu görevlerle mücadele ettiği ve kişisel bir trajedinin ortasında kaldığı ortaya çıkar.Itachi'nin en önemli özelliği, Sharingan göz tekniğini mükemmelleştirmiş olmasıdır. Sharingan, özel bir göz tekniği olup, düşmanların hareketlerini takip etme, genjutsu (illüzyon) yapma ve bazı özel teknikleri kullanma yeteneği sağlar. Itachi, Sharingan'ı son derece ustaca kullanır ve rakiplerine karşı büyük bir avantaj elde eder.Ancak, Itachi'nin hikayesi karmaşıktır ve geçmişi sırlarla doludur. Ailesine ihanet etmek zorunda kalmış ve klanını yok etmiştir. Bu olayların ardındaki gerçeği anlamak, Itachi'nin karakterini ve eylemlerini daha iyi anlamamızı sağlar. Gerçek nedenleri, hükümetin isteğiyle hareket eden ve köyün güvenliğini korumaya çalışan bir ağabey olarak hareket etmek zorunda olduğu ortaya çıkar.`},
            {nickname:"Obito Uchiha",foto:"https://yt3.ggpht.com/9D04MrZE0Ryi6xgeTURZSbyoCmzS686Di2ElgO06iggdi9hdIVwer4RD17szuB1fhGDjLIiufw=s900-c-k-c0x00ffffff-no-rj", sayi:18,article:`Obito Uchiha, ilk olarak Naruto serisinin Shippuden bölümlerinde tanıtılan bir karakterdir. Obito, genç bir ninjayken bir görev sırasında büyük bir trajedi yaşar. Bir kayanın altında sıkışıp kalır gibi görünür.Ancak, aslında Obito, ölmedi ve Madara Uchiha tarafından kurtarılıp tedavi edilir. Madara, Obito'yu manipüle ederek kendi amaçları için kullanır. Obito, Madara'nın etkisi altında kalarak karanlık bir yol izler ve kendini "Tobi" olarak tanıtarak Akatsuki örgütüne katılır.Obito'nun en önemli özelliği, "Kamui" adı verilen bir Mangekyou Sharingan tekniğini kullanabilmesidir. Kamui, Obito'ya özel bir uzay-zaman ninjutsu yeteneğidir. Bu yetenek sayesinde, Obito nesneleri veya kendini diğer bir boyuta aktarabilir ve rakiplerinin saldırılarından kaçabilir.Obito'nun hedefi, İdeal Dünya Projesi olarak bilinen bir planı gerçekleştirmektir. Bu plan, dünyadaki tüm savaşı sona erdirmeyi ve insanları sonsuz bir illüzyon olan "Tsukuyomi" içinde yaşatmayı içerir. Obito, bu planı gerçekleştirmek için Naruto ve arkadaşlarına karşı savaşır ve kötü niyetleriyle bilinir.`},
            {nickname:"Rin Nohara",foto:"https://i.pinimg.com/736x/ac/0f/52/ac0f526f94ceb404cd4849ce13bc61a9.jpg",sayi:19, article:`Rin, Konohagakure'nin (Yaprağın Köyü) üyelerinden biri olan bir ninjadır. Aynı ekiple olan Kakashi Hatake ve Obito Uchiha ile "Altın Üçlü" olarak anılırlar.Rin, sakin ve nazik bir kişiliğe sahip olan bir kunoichi'dir (kadın ninja). Diğer ekip üyelerini desteklemek ve görevlerini tamamlamak için kendi becerilerini kullanır.Rin, özellikle Kakashi Hatake için duygusal bir bağa sahiptir. Ona olan yakınlığı ve sempatisi, Kakashi'nin sert ve soğuk dış görünüşünün altında yumuşak bir yüreğe sahip olduğunu gösterir.Ancak, Rin'in hikayesi trajik bir dönemeç alır. Bir görev sırasında, Rin, Kirigakure'nin (Sisli Köy) tarafından kaçırılır ve Kiri'nin Orochimaru tarafından zihinsel olarak kontrol edilmiş bir "Jinchuriki" olur. Rin, içinde üç kuyruklu bir tilki tailed beast olan "Isobu"ya hapsolmuştur.Rin, köyüne ve ekibine zarar vermemek adına, kendisini feda eder. Kendini Kakashi'nin Raikiri (Chidori) adlı güçlü teknikle öldürmesine izin verir. Bu olay, Kakashi ve Obito'nun hayatlarını derinden etkiler. Rin, Naruto serisindeki kısa süreli gösterilmesine rağmen, Kakashi ve Obito arasındaki duygusal bağın ve onun fedakarlığının önemli bir parçasıdır. Onun hatırası, karakterlerin gelişiminde ve motivasyonlarında önemli bir rol oynar.`},
            {nickname:"Madara Uchiha",foto:"https://i.pinimg.com/videos/thumbnails/originals/83/17/c1/8317c1a0fcb48e4cf08958b5bca7d436.0000001.jpg",sayi:20, article:`Madara Uchiha, Uchiha Klanı'nın liderlerinden biri ve İkinci Shinobi Dünya Savaşı döneminde yaşamış bir ninjadır. Kendisi Uchiha Klanı'nın güçlü Sharingan göz yeteneklerini mükemmelleştiren biridir.Madara, gençken Hashirama Senju ile olan mücadelesiyle ün kazanmıştır. İki güçlü ninja arasındaki rekabet, Konohagakure'nin (Yaprağın Köyü) ve Gölge'nin Köyü arasındaki uzun süren savaşın temel nedenlerinden biridir.Madara, İkinci Shinobi Dünya Savaşı sırasında kendi ölümsüzlüğünü sağlamak için Rinnegan adlı efsanevi göz tekniğini uyandırmayı başarmıştır. Rinnegan, en güçlü göz yeteneklerinden biridir ve pek çok farklı elementin kullanılmasına izin verir. Madara, Rinnegan sayesinde muazzam güç ve yetenekler kazanır.Madara'nın hedefi, Dünya'nın İdeal Projesi olarak adlandırılan bir planı uygulamaktır. Bu plan, dünyayı sürekli bir savaş ve çatışmadan kurtararak sonsuz bir barış ve istikrara kavuşturmayı içerir. Ancak, bu planın arka yüzünde diğer insanların iradesini ve özgürlüğünü yok etmek vardır.`},
            {nickname:"Yahiko",foto:"https://i.pinimg.com/736x/fd/b9/f0/fdb9f0616055a0df436eb1f60dec284a.jpg", sayi:21,article:`Yahiko, Ame Köyü'nde doğmuş ve Büyük Shinobi Savaşları döneminde büyük bir yıkımın içinde yetişmiştir. Kendisi, yoksulluk ve çatışmalarla dolu bir ortamda büyüdü ve dünyadaki adaletsizliklere karşı bir isyan başlatmaya karar verdi.Yahiko, Nagato ve Konan ile birlikte "Akatsuki" adlı bir örgüt kurdu. Akatsuki, dünyadaki savaşların sona ermesini ve barışın sağlanmasını hedefleyen bir gruptu. Yahiko, liderlik rolünü üstlenirken, Nagato (Pain) ise örgütün gücünü temsil ediyordu.Ancak, Yahiko'nun hikayesi trajik bir şekilde sona erer. Orochimaru'nun öncülük ettiği bir komplonun bir parçası olarak, Yahiko kendini feda eder. Bu fedakarlık, örgütün devam etmesi ve Pain'in gücünü kullanarak dünyayı değiştirme hedefini sürdürebilmesi için yapılmıştır.`},
            {nickname:"Nagato Uzumaki",foto:"https://i.pinimg.com/originals/59/df/01/59df012bce2f4a1e3032d5429769ef02.jpg", sayi:22,article:`Nagato, Yahiko ve Konan ile birlikte Ame (Yağmur) Köyü'nde doğmuş ve büyümüştür. Büyük Shinobi Savaşları döneminde, köyü sürekli savaşlarla ve çatışmalarla dolu olmuştur. Nagato ve arkadaşları, dünyadaki adaletsizliklere karşı bir isyan başlatmak için "Akatsuki" adında bir örgüt kurarlar. Nagato'nun özel bir yeteneği olan "Rinnegan" gözleri, onu son derece güçlü kılar. Rinnegan, pek çok farklı göz tekniğini kullanabilme ve doğa elementlerini kontrol edebilme yeteneği veren efsanevi bir göz yeteneğidir. Bu güçlü yetenek sayesinde, Nagato, Akatsuki'nin lideri olarak büyük bir tehdit haline gelir.Akatsuki'nin lideri olarak, Nagato, dünyadaki savaşların sona ermesini ve barışın sağlanmasını hedefler. Ancak, Yahiko'nun ölümü ve geçmişteki travmatik deneyimleri nedeniyle, barışı sağlamak için acı verici bir yöntem benimser. Kendisine "Pain" olarak hitap eder ve ölümle tanımlanan acı çekmeyi dünyaya dayatır.`},
            {nickname:"Konan",foto:"https://i.pinimg.com/736x/69/72/f3/6972f349c73a637d61a3080d3f66168b.jpg", sayi:23,article:`Konan, Ame (Yağmur) Köyü'nde doğmuş ve büyümüş olan bir kunoichi'dir (kadın ninja). Yahiko ve Nagato ile birlikte çocukluğunda aynı köyde yaşar ve Büyük Shinobi Savaşları döneminde yaşanan acı ve çatışmalara şahit olur.Yahiko ve Nagato ile birlikte, adaletsizliklerle dolu bir dünyada barışı ve değişimi sağlamak amacıyla "Akatsuki" adlı bir örgüt kurarlar. Konan, Akatsuki'nin tek kadın üyesidir ve Yahiko'nun ölümünden sonra örgütün lideri olarak Nagato'ya destek olur.Konan'ın benzersiz bir yeteneği vardır. Kendisi, binlerce kağıttan yapılan ve savaşta kullanılan özel kağıt teknikleri olan "Origami" tekniklerini kullanır. Kağıtlarını kendi vücudu gibi manipüle edebilir ve onları hem savunma hem de saldırı amaçlı olarak kullanabilir. Bu yetenek, ona dikkat çeken ve etkileyici bir güç verir.Konan, Akatsuki'nin hedefleri doğrultusunda dünyayı değiştirmek için çaba sarf ederken, eski arkadaşları olan Yahiko ve Nagato'nun hedeflerini ve ideallerini korumak için çaba gösterir. Yahiko'nun mirasını sürdürmeye çalışır ve Akatsuki'nin amacını gerçekleştirmeye yardımcı olur.`},
            {nickname:"Killer Bee",foto:"https://yt3.googleusercontent.com/Q0EVYuqTJObbNAH_pfBisRmM5NehmHFJcyqKi3ctNmIMw4ML-PyIT-DK_PfLgV5dDPQYH-khog=s900-c-k-c0x00ffffff-no-rj", sayi:24,article:`Gerçek adı "B" olan Killer Bee, Kumogakure'nin Hachibi no Kyogyū (Sekiz Kuyruklu Canavar) olarak da bilinen Bijuu'su (Tailed Beast) ile olan Jinchuriki'dir. Hachibi, sekiz kuyruklu bir tilki gibi görünen ve muazzam güce sahip olan bir Bijuu'dur.B, Hachibi'nin gücünü kontrol edebilen nadir Jinchuriki'lerden biridir. Hachibi ile uyum içinde çalışır ve onun güçlerini kendi avantajı için kullanır. B, özellikle rap müziğe olan ilgisiyle ve kendine özgü konuşma tarzıyla tanınır.Killer Bee, Naruto ile dostane bir rekabet içinde olan güçlü bir ninja olarak tanıtılır. İki karakter arasındaki etkileşimler, seride komik ve duygusal anlar sunar. B, Naruto'ya Jinchuriki olarak sahip olduğu güç ve zorluklar hakkında önemli öğretiler verir.`},
            {nickname:"Yamato",foto:"https://vignette.wikia.nocookie.net/naruto/images/f/f7/Yamato_newshot.png/revision/latest?cb=20180920062234", sayi:25,article:`Yamato, Orochimaru tarafından yaratılan İkinci Hokage olan Tobirama Senju'nun hücrelerinin bir parçasıyla deneyler sonucu oluşturulan bir klonudur. Bu nedenle, Yamato, doğal bir şekilde mükemmel bir kontrol yeteneği olan "Mokuton" (Kuşağın Ağacı) olarak bilinen Kekkei Genkai'ye sahiptir.Mokuton, bitki ve ağaçları kontrol edebilme yeteneğidir ve Yamato, bu gücü genellikle büyülü tahterevalliler veya savunma amaçlı devasa ağaç duvarları oluşturmak için kullanır.Yamato, Naruto'nun ve diğer Geninlerin eğitmenliğini yapar. Özellikle Naruto'nun Jinchuriki güçlerini kontrol etmesine ve Nine-Tails (Kurama) ile uyum içinde çalışmasına yardımcı olur. Naruto'nun eğitim sürecinde ona "Kurama Kontrolü" ve "Elementlerin Dengesi" gibi önemli teknikleri öğretir.Naruto Shippuden döneminde, Yamato, Naruto'nun Sasuke'yi bulma ve geri getirme görevine liderlik eder. Team 7 ile birlikte Sasuke'nin izini sürerken zorlu görevlerle karşılaşır.Yamato, genellikle sakin ve olgun bir kişiliğe sahiptir ve diğer karakterler arasında düzen sağlayan bir rol oynar. Aynı zamanda mizahi anlar ve komik tepkileriyle de dikkat çeker.`},
            {nickname:"Kaguya Ōtsutsuki",foto:"https://i.pinimg.com/originals/8d/eb/01/8deb016458f64ba54970337d3ee7d2f1.jpg",sayi:26, article:`Kaguya Ōtsutsuki, evrenin en eski ve en güçlü klanlarından biri olan Ōtsutsuki klanından gelir. Ōtsutsuki klanı, Chakra Ağacı ve Kutsal Meyve gibi güçlü enerji kaynaklarını arayan, dünyaları ve boyutları dolaşan bir klandır. Kaguya, Chakra Ağacı'nın gücünü elde etmek için dünyaya geldi.Kaguya'nın hikayesi, uzun bin yıl öncesine kadar uzanır. Dünyayı ele geçirmek ve sonsuz güce ulaşmak için insanlara hükmetmeye başladı. Kendisine "Tenchu no Sho" denilen güçlü teknikleri kullanarak insanları kontrol etti ve boyutlar arasında seyahat etmeye imkan sağlayan Rinnegan göz yeteneğine sahip oldu.Ancak, Kaguya'nın hikayesi ve amacı, Naruto serisinin sonlarına doğru daha iyi anlaşılır. Naruto ve arkadaşları, Sasuke'nin yardımıyla Kaguya'yı yenmek ve dünyayı tehdit eden tehlikeli planlarını durdurmak için birlikte çalışır.Kaguya, en güçlü Otsutsuki olarak kabul edilir ve neredeyse yenilmezdir. Serinin ilerleyen bölümlerinde, Kaguya'nın arkasındaki gerçek hikaye açıklanır ve klanının geçmişi hakkında daha fazla bilgi edinilir.`},
            {nickname:"Hagoromo Ōtsutsuki",foto:"https://mir-s3-cdn-cf.behance.net/projects/404/07c29f117161029.607049c40e8c5.jpg",sayi:27,article:`Hagoromo, Naruto serisinde "Rikudou Sennin" veya "Altı Yol Yıldızı" olarak bilinir. Kendisi, Chakra'nın doğuşunu ve Shinobi kültürünün temelini oluşturan önemli bir figürdür. O, Rinnegan göz yeteneğine sahiptir ve Bijuuları yaratmıştır. İlk Jinchuriki olarak, Tailed Beast'leri insan vücutlarına hapsetmiştir.Hagoromo, "Sage of the Six Paths" olarak anılan ve Shinobi dünyasındaki barışı sağlamaya çalışan bir bilge olarak tasvir edilir. O, insanlara Chakra'nın kullanımını öğretir ve aynı zamanda dünyayı tehdit eden annesi Kaguya'yı durdurmak için çabalar.Hagoromo'nun en ünlü oğlu, Asura Ōtsutsuki'dir. Asura, Hagoromo'nun iradesini miras alır ve Shinobi dünyasında barışı ve işbirliğini teşvik eder.`},
            {nickname:"Hamura Ōtsutsuki",foto:"https://pm1.narvii.com/5980/bd73d7ed6f6e3e6f437dd25a5d3eb56bd914129f_hq.jpg",sayi:28,article:`Hamura, Kaguya'nın diğer oğludur ve daha az tanınan bir karakterdir. Daha çok Naruto Shippuden döneminde Boruto serisine geçişte öğrenilir. Hamura, annesi Kaguya'nın görevini yerine getirmek için Ay'a gitmiş ve orada yaşamıştır. Kaguya, Dünya'yı terk etmeden önce onu Ay'a göndermiştir.Hamura, ayrı bir klan olan Hyuuga klanının atası olarak kabul edilir ve Ay'daki klanın lideridir. Ayrıca, Tenseigan göz yeteneğine sahiptir ve bu gücü Boruto serisinde önemli bir rol oynar.`},
            {nickname:"Bijuular",foto:"https://cutewallpaper.org/21/all-of-the-tailed-beasts/Naruto-Wallpaper-1920x1080-Tailed-Beast-1920x1080-Naruto-.jpg",sayi:29,article:`Bijuu'lar, Naruto evrenindeki güçlü tailed beastlerdir. Her biri, büyük miktarda chakra ve olağanüstü güçlere sahip olan dokuz farklı tailed beast'ten oluşur. İşte Naruto serisindeki bijuuların listesi:Shukaku: Birinci kuyruklu canavar, Rokubi olarak da bilinir ve kum elementine sahiptir.Matatabi: İkinci kuyruklu canavar, Nibi olarak da bilinir ve mavi alevleri kontrol eder.Isobu: Üçüncü kuyruklu canavar, Sanbi olarak da bilinir ve su elementini kullanır.Son Goku: Dördüncü kuyruklu canavar, Yonbi olarak da bilinir ve ateş elementine sahiptir.Kokuō: Beşinci kuyruklu canavar, Gobi olarak da bilinir ve boğa şeklinde bir canavardır.Saiken: Altıncı kuyruklu canavar, Rokubi olarak da bilinir ve zehir elementine hükmeder.Chōmei: Yedinci kuyruklu canavar, Nanabi olarak da bilinir ve böcek elementine sahiptirGyūki: Sekizinci kuyruklu canavar, Hachibi olarak da bilinir ve boğa şeklinde bir canavardır.Kurama: Dokuzuncu kuyruklu canavar, Kyuubi olarak da bilinir ve uzun süre Naruto'nun içinde hapis kalmıştır. Ateş elementine hakimdir ve güçlü bir yok edici enerjiye sahiptir. Bijuu'lar, Rikudou Sennin (Altı Yol Yıldızı) Hagoromo Ōtsutsuki tarafından yaratılmıştır. `},
        ]

    },
    {
        name: "attack on titan",
        namee:"Attack On Titan",
        kapakfoto: "https://i.ytimg.com/vi/jHJQwsQNSSQ/maxresdefault.jpg",
        main:{
            foto:"https://c.wallhere.com/photos/9d/9e/attack_on_titan_eren_jaeger_shingeki_no_kyojin-571712.jpg!d", article:`"Attack on Titan" (Shingeki no Kyojin), Hajime Isayama tarafından yazılmış ve çizilmiş bir Japon manga serisinden uyarlanan bir anime serisidir.Hikaye, insanoğlunun, devasa boyutlardaki yaratıklar olan "Titanlar" tarafından tehdit edildiği bir distopik dünyada geçmektedir. İnsanlığın hayatta kalma mücadelesini ve büyük surların ardında yaşayan insanların Titan saldırılarından korunma çabalarını anlatır. Ana karakterlerden Eren Yeager, annesinin bir Titan tarafından öldürülmesinin ardından, insanlığı Titanlar'dan kurtarmak ve onlara karşı intikam almak amacıyla "Özel Titan Askeri Birliği"ne katılmaya karar verir. Bu birlik, cesur savaşçılardan oluşur ve Titanlar'la mücadele etmek için duvarların dışına çıkarlar.Eren'in beklenmedik bir şekilde kendini Titan'a dönüştürebilme yeteneği, hikayenin merkezinde önemli bir olayı oluşturur ve insanlık için umut ışığı haline gelir.   "Attack on Titan," aksiyon dolu sahneleri, etkileyici karakter gelişimi ve derin düşündürücü hikayesiyle dikkat çeker. Aynı zamanda, arkadaşlık, fedakarlık, ve insan doğasının karmaşıklığı gibi temaları ele alır. Dünya genelinde geniş bir hayran kitlesi bulunan bu anime serisi, izleyicileri sürükleyici ve etkileyici bir deneyim sunar.`
        },
        karakterler: [
            { nickname: "Eren Yeager", foto: "https://i.pinimg.com/736x/1d/33/ff/1d33ffbf275d438f5bdc7576a66d3cfb.jpg", sayi:1,article:`Eren Yeager,"Attack on Titan" (Shingeki no Kyojin) adlı manga ve animesinin ana karakteridir. Eren, seri boyunca büyüyen ve gelişen bir karakter olarak dikkat çeker.Hikayeye Shiganshina adlı şehirde başlar. Eren, ailesi ve en yakın arkadaşları Mikasa Ackerman ve Armin Arlert ile birlikte yaşamaktadır. Ancak, bu dünya Titan adı verilen dev yaratıkların tehdidi altındadır. Bir gün, Colossal Titan ve Armored Titan adı verilen iki dev Titan, devasa duvarları aşarak Shiganshina'yı basar ve insanların yaşadığı bölgeyi harap ederler. Eren, annesini Titanlar tarafından kaybeder ve bu olay hayatının dönüm noktası olur.Eren, ailesini ve insanlığın maruz kaldığı acıları unutmamış, Titanların içine duyduğu öfkeyle dolmuştur. Amacı, Titanları yok etmek ve insanların özgürlüğünü geri kazanmaktır. Titanlara karşı savaşmak için kendi gücünü geliştirmeye karar verir ve Özel Kuvvetler Birimine katılarak eğitim alır.Ancak, Eren'in özel bir yeteneği vardır; kendini Titan'a dönüştürebilme kabiliyetine sahiptir. Bu yetenek, onun ve insanlık için hem bir avantaj hem de büyük bir sorumluluktur. Eren'in içindeki bu gücü kontrol etme ve onunla başa çıkma süreci, hikayenin önemli bir teması haline gelir.`},
            { nickname: "Mikasa Ackerman", foto: "https://i.pinimg.com/originals/2b/58/0e/2b580e5a7b06b3ebc14749f4c20a5a4e.jpg", sayi:2,article: `Mikasa oldukça sakin, soğukkanlı ve dikkatli bir kişiliğe sahiptir. Savaşta son derece yetenekli bir savaşçıdır. Eren'in ailesi tarafından evlat edinilmiş ve onunla çocukluktan beri büyümüştür. Ailesini kaybettikten sonra Eren'e olan sadakati çok güçlü hale gelmiştir.Mikasa, Eren'i korumak için her türlü fedakarlığı yapmaktan çekinmez. Onun güvenliği için risk alır ve savaşta etkileyici becerilerini kullanarak onu destekler. Ancak, aşırı korumacılığı bazen onun hırslı ve sert biri olarak algılanmasına yol açar.Mikasa, Attack on Titan'ın temel karakterlerinden biri olarak, hikayede önemli bir rol oynar ve izleyicilerin ve okuyucuların sevgisini kazanmıştır. Eren ve Mikasa arasındaki bağ, serinin duygusal bir yönü olarak vurgulanır ve ikilinin birlikte geçirdiği zorluklar onları daha da yakınlaştırır.` },
            {nickname:"Armin Arlert",foto:"https://i.pinimg.com/originals/7e/b0/54/7eb0549c345268f86fb187c51f371100.png",sayi:3,article:`Armin, diğer arkadaşlarına göre daha ince yapılı ve kırılgan görünüme sahiptir. İlk başta utangaç ve korkak biri gibi görünebilir, ancak zekası ve stratejik düşünme becerileri onu diğerlerinden farklı kılar. Analitik düşünme yeteneği, sıkıştıkları durumlarda çözüm bulmalarına yardımcı olur.Seride, Armin'in en büyük gücü zekası ve bilgisi olur. Titanlarla mücadelede farklı bir rol oynar ve özellikle taktiksel kararlar alarak arkadaşlarına destek verir. Cesareti zamanla artar ve karakteri serinin ilerleyen bölümlerinde büyük bir gelişim gösterir.Armin, arkadaşı Eren'in en iyi dostlarından biri olarak, Eren ve Mikasa ile birlikte insanlığın Titanlarla olan savaşında önemli bir rol oynar. Karakterinin insanlık, fedakarlık ve arkadaşlık gibi temalarda etkileyici bir yönü vardır ve izleyiciler tarafından sevilir.`},
            {nickname:"Levi Ackerman",foto:"https://mobimg.b-cdn.net/v3/fetch/ff/ff955fac0f76d3e51fc5cc24c39924f0.jpeg",sayi:4,article:`Levi, insanlık için savaşan Özel Kuvvetler Birimi'nde (Survey Corps) yer alan bir askerdir ve bu birimdeki en yetenekli ve saygı duyulan savaşçılardan biridir. Onun takım lideri olarak liderlik becerileri ve savaş yeteneği efsanevi olarak nitelendirilir.Karakteristik olarak, Levi oldukça sessiz ve soğukkanlı bir kişiliğe sahiptir. Olaylara pratik bir bakış açısıyla yaklaşır ve duygularını genellikle göstermez. Ancak, insanlara karşı bir çeşit koruyucu içgüdüsü vardır ve sevdikleri için çaba gösterir.Levi, özellikle hareket etme yeteneği ve manevra kabiliyetiyle ün salmıştır. O, 3D Maneuver Gear adı verilen özel bir ekipman kullanarak hızlı ve çevik hareket edebilir, duvarlara tırmanabilir ve Titanlarla etkili bir şekilde savaşabilir. Bu nedenle, Titanlarla olan savaşta en büyük varlık olarak kabul edilir.Levi'nin geçmişi ve kökeni seride önemli bir tema haline gelir ve izleyicilere onun arka planını ve ne kadar zorlu bir hayatı olduğunu gösterir. Buna rağmen, savaşta ve zorlu koşullarda bile kendi değerlerine ve prensiplerine bağlı kalmayı başarır.`},
            {nickname:"Historia Reiss",foto:"https://i.pinimg.com/originals/21/e4/0b/21e40b03dbfe05cd27a63207c6933a14.jpg",sayi:5,article:`Historia, aslen Krista Lenz adıyla tanınır. İlk olarak, alçakgönüllü ve kırılgan bir kişilik olarak tanıtılır. Onu insanların gözünde önemsiz ve yetersiz biri olarak görülür. Ancak, aslında gerçek kimliği, Reiss ailesinin bir üyesi olduğu ve tahtın gerçek varisi olduğu gerçeğidir.Hikayenin ilerleyen bölümlerinde, Historia'nın gerçek kimliği ve ailesinin sırları ortaya çıkar. Babası Rod Reiss, sahte bir kral olarak bilinen ve insanlığın gerçek düşmanlarının peşinden giden kötü niyetli bir karakterdir. Historia, bu sırları keşfettikçe kendi kimliği ve amacı üzerine sorgulamalar yaşar.Historia, zamanla güçlü bir karakter haline gelir ve kendi değerlerine, arkadaşlarına ve insanlığın iyiliğine bağlılık gösterir. Zorlu durumlarla karşılaştığında bile cesur ve kararlı bir şekilde hareket eder.İnsanların umutsuzluğu ve savaşın acımasızlığına rağmen, Historia insanların daha iyi bir dünya için mücadele etmeye ve aydınlık bir gelecek için çabalamaya teşvik eder.`},
            {nickname:"Erwin Smith",foto:"https://i.pinimg.com/originals/3c/83/8a/3c838a274b952fa0f807edd691a7289c.png",sayi:6,article:`Erwin, insanların yaşadığı son şehir olan Shiganshina'nın dışında doğmuştur. Genç yaşlardan itibaren Titanların gerçek doğası ve dünyanın geri kalanının sırları hakkında merak duymuştur. Amacı, insanlığın sınırlarını genişletmek ve gerçeği keşfetmektir.Erwin, stratejik düşünme becerileri ve liderlik yetenekleriyle tanınır. İnsanlığın düşmanlarına karşı olan savaşta cesurca ilerler ve arkadaşlarına ilham verir. Amacı için her türlü fedakarlığı yapmaktan çekinmez.Kendisinin ve diğer askerlerin hayatını riske atarak savaşta liderlik yapar. Amacı, insanlığı Titanlardan kurtarmak ve dünyayı dışarıdan gelen tehditlerden korumaktır.Erwin, insan doğasını ve gerçekleri anlama arayışında olan bir karakterdir. Aynı zamanda, kişisel hedeflerine ulaşmak için insanların inanç ve desteğinin ne kadar önemli olduğunu keşfeder.`},
            {nickname:"Jean Kirstein",foto:"https://i.pinimg.com/originals/70/56/be/7056be06486fd4e3da996df554568081.jpg",sayi:7,article:`Jean, başlangıçta Titanlarla olan savaşta daha rahat bir hayat arzulayan ve başkalarına nazaran daha bencil bir karakter olarak tanıtılır. Ailesinin ekonomik durumunun kötü olması nedeniyle, Survey Corps'a katılmak yerine daha güvenli bir iş arzulamaktadır.Ancak, zamanla Eren ve diğer arkadaşlarının cesaretine ve fedakarlığına tanık oldukça, kendi değerlerini ve hayatının amacını sorgulamaya başlar. Özellikle Eren'in öfkesine ve kararlılığına ilham olur ve onun gibi bir savaşçı olmak için çabalar.Jean, eğitim ve savaş deneyimleri sayesinde olgunlaşır ve cesur bir savaşçı haline gelir. Survey Corps üyeleri arasında liderlik özellikleri ve takım çalışması becerileri ile tanınır. Titanlara karşı verilen savaşta, diğer askerlere örnek olur ve takımın bir parçası olarak kendini kanıtlar.Serinin ilerleyen bölümlerinde Jean'in karakteri önemli bir gelişim geçirir ve içsel bir dönüşüm yaşar. Cesaret ve insanlığın kaderiyle yüzleşirken, özgünlüğü ve empati yeteneğiyle dikkat çeker.`},
            {nickname:"Connie Springer",foto:"https://i.pinimg.com/736x/3a/8a/e4/3a8ae4a8c9fb6e7dd10573dc0befcd04.jpg",sayi:8,article:`Connie, serinin başlangıcında, köyündeki bir Titan saldırısı sonucunda ailesini kaybeder. Bu trajik olayın ardından, insanların güvenliğini sağlamak ve Titanlara karşı savaşmak için Survey Corps'a katılır.Connie, diğer arkadaşlarına göre daha neşeli ve esprili bir kişiliğe sahiptir. Zorlu durumlarda bile mizah duygusunu korur ve moral desteği sağlar. Cesareti ve neşesi, Survey Corps'un zorlu görevlerinde arkadaşlarına ilham verir.Karakteristik olarak, Connie savaşta pratik ve hızlı bir şekilde düşünme yeteneğine sahiptir. Kendisi bir savaşçı olmasa da, Survey Corps ekibinin değerli bir üyesidir ve takım çalışmasına büyük önem verir.Connie, Titan sırları ve insanların dünyasının gerçek doğası hakkında meraklıdır ve arkadaşlarıyla birlikte gerçeği keşfetmek için çaba sarf eder.Connie Springer, "Attack on Titan" serisinde, sadık arkadaşlığı ve neşeli kişiliğiyle izleyicilerin ve okuyucuların sevdiği önemli bir karakterdir. Savaşın acımasızlığına rağmen, içindeki iyilik ve umut dolu kişiliğiyle dikkat çeker.`},
            {nickname:"Sasha Blouse",foto:"https://i.pinimg.com/originals/f3/90/d3/f390d38aea209b4275355f6b1bb4101c.jpg",sayi:9,article:`Sasha, küçük bir köyde doğmuş ve yetişmiştir. Annesinin onu köy dışında farklı insanlarla tanıştırmak için sürekli götürdüğü gibi, avlanma ve doğada yaşamayı seven bir karakterdir. Bu yetenekleri ve doğal içgüdüleri, Survey Corps'a katıldığında ona avantaj sağlar.Karakteristik olarak, Sasha oldukça açık sözlü, doğal ve samimi bir kişiliğe sahiptir. Yiyeceklere olan düşkünlüğü ve özellikle patates sevgisiyle dikkat çeker. Kendi isteği dışında "Patates Kız" adıyla anılmasına rağmen bu lakabı kucaklar ve gururla taşır. Sasha, cesur ve becerikli bir savaşçıdır. Yüksek hızda koşma ve keskin nişancılık yetenekleri onu savaşta diğerlerinden ayırır. Titanlarla yapılan mücadelede gösterdiği üstün yetenekleri sayesinde ekibin önemli bir üyesi olur. Sasha, insanlığın umutları ve zorlukları arasında bir dengeyi temsil eder. Savaşta yüzleştiği acımasızlığa rağmen, arkadaşları ve insanların güvenliği için mücadele etmeye devam eder.`},
            {nickname:"Hange Zoë",foto:"https://images.hdqwalls.com/download/hange-zoe-attack-on-the-titan-28-2048x2048.jpg",sayi:10,article:`Hange Zoe, titiz bir bilim insanı ve araştırmacıdır. Titanlar hakkındaki sırları keşfetmeye, onların doğasını anlamaya ve insanlığın düşmanlarına karşı üstünlük sağlayacak stratejiler geliştirmeye odaklanır.Karakteristik olarak, Hange dikkatli ve meraklı bir kişiliğe sahiptir. Titanlarla yakından ilgilenir ve onların davranışlarını, fizyolojilerini ve motivasyonlarını anlamak için özel deneyler yapar. Bu merakı ve çabaları, Titanlara karşı yapılan savaşta insanlığın lehine büyük katkılar sağlar.Hange, insanların düşmanlarına karşı mücadele etmek için cesur ve kararlı bir liderdir. Titanlarla dolu tehlikeli ortamlarda bile bilim ve stratejiye dayalı akılcı kararlar alır.Aynı zamanda, Hange, insanların doğasını anlamaya ve insanlar arasındaki ilişkileri incelemeye de merak duyar. Savaşın ve trajedinin getirdiği zorluklarla yüzleşirken, insanlık hakkındaki görüşleri de değişime uğrar.`},
            {nickname:"Reiner Braun",foto:"https://wallpapercave.com/wp/wp4524633.png",sayi:11,article:`Reiner, serinin başlangıcında Eren ve diğer ana karakterlerle aynı öğrenci grubunda yer alan sıradan bir genç gibi görünür. Ancak aslında Reiner, Eldia adı verilen başka bir ırka mensup ve Titanların gerçek varlığı hakkında gizli bir görevle gönderilmiş bir Marley casusudur.Reiner, çoklu kişilik bozukluğu yaşayan karmaşık bir karakterdir. Bir yanda, arkadaş canlısı ve dostça bir görüntü verirken, diğer yanda Marley'yi ve kendi ırkını koruma göreviyle sıkıntılı bir çatışma içindedir.Kendisi, Titan Sırrı'nın anahtarını elinde bulundurarak insanların ve Titanların gerçek doğasını açığa çıkarma çabalarında rol oynar. Ancak zamanla, iki ayrı kimlik arasındaki mücadelesi onun zihinsel sağlığını etkilemeye başlar.Reiner Braun, savaşta cesur ve güçlü bir savaşçıdır. Survey Corps üyeleri arasında liderlik becerileri ve taktiksel zekasıyla dikkat çeker. Ancak kendi iç çatışmaları, izleyicilerde ona karşı karmaşık duygular uyandırır.`},
            {nickname:"Annie Leonhart",foto:"https://i.pinimg.com/originals/2d/76/1c/2d761c6c685161af464ff1f5d17a8346.jpg",sayi:12,article:`Annie, başlangıçta diğer ana karakterlerle birlikte Eren, Mikasa ve Armin gibi Survey Corps üyeleri arasında yer alır. Dışa dönük bir kişiliğe sahip değildir ve genellikle sessiz ve duygusal olarak mesafeli görünür.Annie aslında Marley hükümetinin gizli bir ajanıdır ve Titan Sırrı'nı ortaya çıkaracak önemli bilgilere sahiptir. Onun gerçek kimliği, serinin ilerleyen bölümlerinde açığa çıkar ve izleyiciler için büyük bir sürpriz olur.Karakteristik olarak, Annie son derece yetenekli bir savaşçıdır ve "Female Titan" olarak da anılır. Bu özel Titan formunu kontrol etme ve güçlü saldırılar gerçekleştirme yeteneğine sahiptir. Bu, onu insanların en güçlü düşmanları olan Titanlara karşı çok etkili bir silah haline getirir.Annie, insanların ve Marley'nin arasındaki karmaşık politikalar ve güç oyunlarının bir parçasıdır. Kendi iç çatışmaları ve görevi arasındaki çelişkiler, onu daha da derin bir karakter yapar.Annie Leonhart, "Attack on Titan" serisinde, gizemli ve karizmatik kişiliği, güçlü dövüş yetenekleri ve karmaşık geçmişiyle izleyicilerin ve okuyucuların ilgisini çeken önemli bir karakterdir.`},
            {nickname:"Zeke Yeager",foto:"https://image.myanimelist.net/ui/5LYzTBVoS196gvYvw3zjwLjPgGMQyjClQAQRprOFb-8",sayi:13,article:`Zeke, Grisha Yeager'ın oğludur ve doğuştan bir Eldia'lıdır. Ancak ailesi, Marley'nin hükümeti için casusluk yapmak üzere Eldia'ya gönderildiği için karmaşık bir geçmişi vardır.Marley hükümetine sadık bir şekilde hizmet eden Zeke, Titan gücünü elinde bulunduran ve Beast Titan olarak da bilinen güçlü bir Titandır. Titan yeteneklerini ustaca kullanır ve savaşta stratejik bir rol oynar.Karakteristik olarak, Zeke, soğukkanlı, zeki ve hesaplı bir kişiliğe sahiptir. Marley'nin amacına hizmet etmek için insanlığın geleceği üzerinde büyük planları vardır ve Titan Sırrı'nı kullanarak insanlığı kontrol etmeyi amaçlar.Zeke, insanların ve Titanların gerçek doğasını keşfetme konusundaki araştırmaları ve bilgeliği ile dikkat çeker. Aynı zamanda ailesi ve geçmişiyle olan ilişkisi, karakterinin derinliğini arttırır.`},
            {nickname:"Kenny Ackerman",foto:"https://i.pinimg.com/originals/fa/56/3a/fa563a9a7baa354ab4681669df3c2a68.png",sayi:14,article:`Kenny Ackerman, "Attack on Titan" (Shingeki no Kyojin) serisindeki önemli yan karakterlerden biridir ve Ackerman ailesinin bir üyesidir. Eski bir suikastçı ve suçludur, bu nedenle "Kenny the Ripper" (Kenny Katili) olarak da bilinir.Kenny, sert ve kavgacı bir kişiliğe sahiptir. Soğukkanlı ve acımasız bir şekilde Marley hükümetine hizmet eder ve onun çıkarları için çeşitli suikast görevlerini üstlenir. Suikastçı olarak ün yapmıştır ve silahları ustalıkla kullanarak düşmanlarına karşı acımasızca mücadele eder.Marley hükümetine olan sadakatinin yanı sıra, Ackerman ailesinin geçmişi ve ilişkileri de karakteri etkiler. Mikasa Ackerman'ın amcasıdır ve onun hayatında önemli bir rol oynamıştır. Bu nedenle, Mikasa ile aralarındaki aile bağları seride önemli bir tema haline gelir.Kenny'nin karakteri, serinin ilerleyen bölümlerinde daha da derinleşir. Mikasa'nın güvenliğini sağlamak ve onu korumak için önemli bir fedakarlık yapar. Bu değişim, onun sadece soğuk bir suikastçı olmadığını, aynı zamanda ailesine ve özellikle Mikasa'ya karşı duygusal bir bağlılık taşıdığını gösterir.Kenny Ackerman, serideki sırlar ve aile bağları sayesinde ilgi çekici bir yan karakter haline gelir. Mikasa Ackerman'ın aile geçmişini ve onun kimliğini anlamak açısından da önemli bir rol oynar.`},
            {nickname:"Carla Yeager",foto:"https://i.pinimg.com/originals/c9/13/17/c913173517e4bcc337a5a47593862b33.jpg",sayi:15,article:`Carla, Eren, Mikasa ve Armin gibi genç karakterlerin yaşadığı Shiganshina kasabasında yaşamaktadır. Eren'in annesi olarak, sevgi dolu, fedakar ve koruyucu bir anne figürüdür. Ailesine ve çevresine sıcak bir atmosfer sunar.Ancak Carla, serinin başlangıcındaki trajik olaylarda hayatını kaybeder. Titanların beklenmedik bir saldırısı sonucunda, Wall Maria'nın yıkılması sırasında Eren ve Mikasa'nın gözleri önünde bir Titan tarafından saldırıya uğrar. Bu olay, Eren ve arkadaşlarının savaşmaları ve Titanlarla mücadeleye girişmelerinin temel motivasyonlarından biri olur.Carla Yeager'ın trajik ölümü, Eren'in kişisel bir dönüşüm geçirmesine ve insanlığı korumak için büyük bir kararlılık kazanmasına neden olur. Bu olay, Eren'in Titanlarla ve Marley hükümetiyle olan mücadelesinin önemli bir itici gücüdür.`},
            {nickname:"Ymir Fritz",foto:"https://i.pinimg.com/originals/97/13/08/971308a2106ec86111dd02d243ea2a2a.jpg",sayi:16,article:`Ymir Fritz, bilinen dünyanın ötesindeki, gerçekçi olmayan bir geçmişi olan efsanevi bir figürdür. Eldia ve Marley gibi devletlerin, hatta Titanların ve insanlığın kökenine dayanan temel bir mitolojiye sahiptir.Efsaneye göre, Ymir Fritz, bin yıllar önceki "Yeraltı Tanrıçası" olarak adlandırılan devasa bir Titan'a dönüşmüştür. Bu dönüşüm, ona inanılmaz güçler ve uzun ömür vermiştir. İnsanlık tarihinin başlangıcı olarak kabul edilen Ymir Fritz'in dönüşümü, Titanlar ve Titan Yetenekleri'nin kaynağı olarak kabul edilir.Efsaneye göre, Ymir Fritz, Titan güçlerini ilk kullanan kişi olmuş ve üç büyük çizme (Devil of All Earth) adında üç farklı güçlü Titan'a bölünmüştür. Bu üç büyük Titan, sonraki yıllarda Eldia ve Marley gibi devletlerin yönetici sınıflarının ve hükümetlerinin kökeni olmuştur.Ymir Fritz'in hikayesi ve mitolojisi, "Attack on Titan" serisinin temel taşlarından biridir ve serinin gidişatını derinden etkiler.`},
            {nickname:"Grisha Yeager",foto:"https://wallpapercave.com/wp/wp8801217.jpg",sayi:17,article:`Grisha Yeager, Eldia'nın duvarlarında yaşayan bir Eldia'lı olarak tanıtılır. Eldia toplumu içinde doktor olarak çalışır ve barışçıl bir yaşam sürer. Ancak, Marley hükümetinin duvarların dışındaki Eldia toplumunu baskı altında tutması ve Eldia'nın tarihine ilişkin gerçekleri keşfetmesiyle hayatı değişir.Marley hükümetinin gizli bilgilerini öğrenen Grisha, Eldia'nın özgürlüğünü ve insanlığın geleceğini kurtarmak için savaşmaya karar verir. Eren Yeager gibi, Titan Yeteneklerine sahip olabilen bir Titan olan "Attack Titan"ın sahibi olur.Grisha'nın Titan Yeteneklerini kullanarak, Eren Yeager'a da Titan güçlerini aktarır. Bu, serinin ana hikayesinin temel taşlarından biridir ve Eren'in Titan Yeteneklerini kullanma ve Marley hükümetiyle mücadele etme yolculuğunu başlatır.Grisha Yeager'ın geçmişi ve ailesi, seride önemli olayların temelini oluşturur. Ayrıca, serinin ilerleyen bölümlerindeki sırların ve Marley hükümeti ile Eldia'nın karmaşık ilişkilerinin açığa çıkmasına katkı sağlar.Grisha Yeager, "Attack on Titan" serisinde, sırlarla dolu geçmişi, ailesiyle olan ilişkisi ve Titan Yetenekleri'nin kullanımı ile dikkat çeken önemli bir karakterdir. Hikayeye ve ana karakterlerin gelişimine büyük bir etki yapar ve serinin merak uyandıran unsurlarından birini oluşturur.`},
            {nickname:"Floch Forster",foto:"https://i.pinimg.com/originals/0d/49/64/0d4964c56251584676f0cbb8bbce1002.jpg",sayi:18,article:`Grisha Yeager, Eldia'nın duvarlarında yaşayan bir Eldia'lı olarak tanıtılır. Eldia toplumu içinde doktor olarak çalışır ve barışçıl bir yaşam sürer. Ancak, Marley hükümetinin duvarların dışındaki Eldia toplumunu baskı altında tutması ve Eldia'nın tarihine ilişkin gerçekleri keşfetmesiyle hayatı değişir.Marley hükümetinin gizli bilgilerini öğrenen Grisha, Eldia'nın özgürlüğünü ve insanlığın geleceğini kurtarmak için savaşmaya karar verir. Eren Yeager gibi, Titan Yeteneklerine sahip olabilen bir Titan olan "Attack Titan"ın sahibi olur.Grisha'nın Titan Yeteneklerini kullanarak, Eren Yeager'a da Titan güçlerini aktarır. Bu, serinin ana hikayesinin temel taşlarından biridir ve Eren'in Titan Yeteneklerini kullanma ve Marley hükümetiyle mücadele etme yolculuğunu başlatır.Grisha Yeager'ın geçmişi ve ailesi, seride önemli olayların temelini oluşturur. Ayrıca, serinin ilerleyen bölümlerindeki sırların ve Marley hükümeti ile Eldia'nın karmaşık ilişkilerinin açığa çıkmasına katkı sağlar.Grisha Yeager, "Attack on Titan" serisinde, sırlarla dolu geçmişi, ailesiyle olan ilişkisi ve Titan Yetenekleri'nin kullanımı ile dikkat çeken önemli bir karakterdir. Hikayeye ve ana karakterlerin gelişimine büyük bir etki yapar ve serinin merak uyandıran unsurlarından birini oluşturur.`},
        ]

    },
    {
        name: "death note",
        namee:"Death Note",
        kapakfoto: "https://banafikirver.com/images/posts/2021/05/post-1620556153-7824-death-note.webp",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" }
        ]

    },
    {
        name: "91 days",
        namee:"91 Days",
        kapakfoto: "https://banafikirver.com/images/posts/2021/05/post-1620556173-8849-91-days.webp",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" }
        ]

    },
    {
        name: "sword art online",
        namee:"Sword Art Online",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" }
        ]

    },
    {
        name: "tokyo ghoul",
        namee:"Tokyo Ghoul",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" }
        ]

    },
    {
        name: "my hero acedemia",
        namee:"My Hero Acedemia",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" }
        ]

    },
    {
        name: "hunter x hunter",
        namee:"Hunter x Hunter",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" }
        ]

    },
    {
        name: "kimi no na wa",
        namee:"Kimi no Na wa",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" }
        ]

    },
    {
        name: "jujutsu kaisen",
        namee:"Jujutsu Kaisen",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" }
        ]

    },
    {
        name: "no game no life",
        namee:"No Game No Life",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" },
            { nickname: "", foto: "", article: "" }
        ]

    },
    {
        name: "",
        namee:"",
        kapakfoto: "",
        main:{
            foto:"", article:""
        },
        karakterler: [
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" },
            { nickname: "", foto: "",sayi:1, article: "" },
            { nickname: "", foto: "", sayi:1,article: "" }
        ]

    },
    












]

module.exports = about;